baseURL: "https://sarahmantell.page/"
title: "Sarah P. Mantell"
defaultContentLanguage: en
assetDir: "assets"
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3

build:
  buildStats:
    enable: true
